name: Atividade Modulo 4

on:
   push:
      branches: [ "main" ]
   
   pull_request:
      branches: [ "main" ]

   schedule:
      - cron: '30 1 * * 5 '  # executa toda sexta 01:30

jobs:
    
    build:
     - name: First interaction
    with:
    # Token for the repository. Can be passed in using {{ secrets.GITHUB_TOKEN }}
    repo-token: 
    # Comment to post on an individual's first issue
    issue-message: # optional
    # Comment to post on an individual's first pull request
    pr-message: # optional
